(() => {
  "use strict";
  const P = window.MonsterLinksParts || {};
  window.MonsterLinksData = {
    SAVE_KEY:P.SAVE_KEY,
    SLOT_PREFIX:P.SLOT_PREFIX,
    ACTIVE_SLOT_KEY:P.ACTIVE_SLOT_KEY,
    SLOT_COUNT:P.SLOT_COUNT,
    GAME_VERSION:P.GAME_VERSION,
    SAVE_SCHEMA_VERSION:P.SAVE_SCHEMA_VERSION,
    DEV_PASSWORD:P.DEV_PASSWORD,
    BALANCE:P.BALANCE || {},
    MAX_PARTY:P.MAX_PARTY,
    MAX_LEVEL:P.MAX_LEVEL || 100,
    PLAYER_MAX_RANK:P.PLAYER_MAX_RANK || 30,
    PLAYER_RANK_EXP:P.PLAYER_RANK_EXP || [],
    PARTY_SLOT_LIMIT:P.PARTY_SLOT_LIMIT || P.MAX_PARTY,
    TYPES:P.TYPES,
    TYPE_CHART:P.TYPE_CHART,
    PERSONALITIES:P.PERSONALITIES,
    SKILLS:P.SKILLS,
    MONSTERS:P.MONSTERS,
    RANK:P.RANK,
    ITEMS:P.ITEMS,
    SHOP_ITEMS:P.SHOP_ITEMS,
    DROPS:P.DROPS,
    QUESTS:P.QUESTS,
    STAGES:P.STAGES,
    ARENA_RANKS:P.ARENA_RANKS,
    RECIPE_GROUPS:P.RECIPE_GROUPS,
    RECIPE_LIST:P.RECIPE_LIST,
    RECIPES:P.RECIPES
  };
})();
