(() => {
  "use strict";
  const P = window.MonsterLinksParts = window.MonsterLinksParts || {};
  P.ITEMS = {
    force_ring:{name:"ちからのリング",icon:"💍",image:"assets/images/items/force_ring.png",kind:"accessory",price:95,desc:"攻撃力が少し上がる基本アクセサリー。",stat:{atk:5}},
    guard_stone:{name:"まもりの石",icon:"🪨",image:"assets/images/items/guard_stone.png",kind:"accessory",price:95,desc:"守備力が少し上がる基本アクセサリー。",stat:{def:5}},
    swift_feather:{name:"はやての羽",icon:"🪶",image:"assets/images/items/swift_feather.png",kind:"accessory",price:95,desc:"素早さが少し上がる基本アクセサリー。",stat:{spd:5}},
    mage_charm:{name:"まどうの首飾り",icon:"🔮",image:"assets/images/items/mage_charm.png",kind:"accessory",price:110,desc:"賢さが少し上がる魔法向けアクセサリー。",stat:{wis:5}},
    life_drop:{name:"命のしずく",icon:"❤️",image:"assets/images/items/life_drop.png",kind:"accessory",price:125,desc:"最大HPが上がる安定アクセサリー。",stat:{hp:20}},
    mana_shell:{name:"マナシェル",icon:"🐚",image:"assets/images/items/mana_shell.png",kind:"accessory",price:120,desc:"最大MPが上がる特技向けアクセサリー。",stat:{mp:12}},
    woodland_crown:{name:"森王の冠",icon:"👑",image:"assets/images/items/woodland_crown.png",kind:"accessory",price:0,desc:"草原ボスが落とすレア装備。HPと守備が上がる。",stat:{hp:28,def:4}},
    ore_core:{name:"鉱王の核",icon:"🟤",image:"assets/images/items/ore_core.png",kind:"accessory",price:0,desc:"洞くつボスが落とすレア装備。守備が大きく上がる。",stat:{def:11,atk:3}},
    tide_pearl:{name:"潮騒の真珠",icon:"🦪",image:"assets/images/items/tide_pearl.png",kind:"accessory",price:0,desc:"湖畔ボスが落とすレア装備。MPと賢さが上がる。",stat:{mp:24,wis:7}},
    volcano_fang:{name:"火山竜の牙",icon:"🦷",image:"assets/images/items/volcano_fang.png",kind:"accessory",price:0,desc:"火山ボスが落とすレア装備。攻撃とHPが上がる。",stat:{hp:22,atk:10}},
    astral_orb:{name:"星晶オーブ",icon:"🌌",image:"assets/images/items/astral_orb.png",kind:"accessory",price:0,desc:"星晶の塔ボスが落とす最上位アクセサリー。全能力が上がる。",stat:{hp:25,mp:12,atk:7,def:7,spd:7,wis:7}},
    frost_scale:{name:"氷竜の鱗",icon:"❄️",image:"assets/images/items/frost_scale.png",kind:"accessory",price:0,desc:"霜降り雪原ボスが落とすレア装備。HP・守備・賢さが上がる。",stat:{hp:35,def:9,wis:6}},
    arc_core:{name:"雷機のコア",icon:"⚡",image:"assets/images/items/arc_core.png",kind:"accessory",price:0,desc:"雷鳴遺跡ボスが落とすレア装備。攻撃・素早さ・賢さが上がる。",stat:{atk:9,spd:9,wis:8}},
    prism_feather:{name:"虹晶の羽飾り",icon:"🌈",image:"assets/images/items/prism_feather.png",kind:"accessory",price:0,desc:"虹晶聖域ボスが落とす最高位アクセサリー。全能力が大きく上がる。",stat:{hp:40,mp:20,atk:10,def:10,spd:10,wis:10}},
    mire_orb:{name:"毒沼オーブ",icon:"🟢",image:"assets/images/items/mire_orb.png",kind:"accessory",price:0,desc:"毒霧の沼地で見つかる妖しい珠。MPと賢さが伸びる。",stat:{mp:14,wis:10}},
    venom_crown:{name:"毒竜の冠",icon:"☠️",image:"assets/images/items/venom_crown.png",kind:"accessory",price:0,desc:"ヴェノムハイドラが落とす冠。攻撃と素早さが大きく上がる。",stat:{atk:12,spd:8}},
    ancient_gear:{name:"古代機心",icon:"⚙️",image:"assets/images/items/ancient_gear.png",kind:"accessory",price:0,desc:"アークマシンが落とす動力炉。攻撃・守備・素早さが上がる。",stat:{atk:10,def:12,spd:6}},
    bronze_emblem:{name:"低ランク闘章",icon:"🥉",image:"assets/images/items/bronze_emblem.png",kind:"accessory",price:0,desc:"低ランク限定大会の証。HPと攻撃が上がる。",stat:{hp:35,atk:8}},
    slime_medal:{name:"ぷるぷるメダル",icon:"🫧",image:"assets/images/items/slime_medal.png",kind:"accessory",price:0,desc:"スライム杯の記念メダル。HP・MP・素早さが上がる。",stat:{hp:30,mp:18,spd:8}},
    element_badge:{name:"属性王のバッジ",icon:"💠",image:"assets/images/items/element_badge.png",kind:"accessory",price:0,desc:"属性別大会の勝者に贈られるバッジ。賢さと素早さが上がる。",stat:{mp:18,spd:10,wis:12}},
    ex_champion_core:{name:"EX覇者のコア",icon:"🏆",image:"assets/images/items/ex_champion_core.png",kind:"accessory",price:0,desc:"EX大会の覇者だけが持つコア。全能力が大きく上がる。",stat:{hp:55,mp:28,atk:14,def:14,spd:14,wis:14}},
    abyss_pearl:{name:"深淵の真珠",icon:"🔵",image:"assets/images/items/abyss_pearl.png",kind:"accessory",price:0,desc:"深海神殿で見つかる真珠。MP・賢さ・守備が上がる。",stat:{mp:26,def:8,wis:12}},
    leviathan_scale:{name:"海竜の鱗",icon:"🐉",image:"assets/images/items/leviathan_scale.png",kind:"accessory",price:0,desc:"アビスリヴァイアが落とす鱗。HP・守備・賢さが上がる。",stat:{hp:55,def:14,wis:10}},
    demon_horn:{name:"魔角のチャーム",icon:"🩸",image:"assets/images/items/demon_horn.png",kind:"accessory",price:0,desc:"魔界門の魔物が持つ角。攻撃と賢さが上がる。",stat:{atk:13,wis:12}},
    chaos_crown:{name:"混沌王冠",icon:"👑",image:"assets/images/items/chaos_crown.png",kind:"accessory",price:0,desc:"デモンロードが落とす王冠。全能力とHPが上がる。",stat:{hp:70,mp:32,atk:16,def:16,spd:12,wis:16}},
    sky_shard:{name:"天空晶片",icon:"💎",image:"assets/images/items/sky_shard.svg",kind:"accessory",price:0,desc:"天空遺跡に漂う魔力の結晶。MP・素早さ・賢さが上がる。",stat:{mp:20,spd:12,wis:12}},
    aether_wing:{name:"蒼天の羽",icon:"🪽",image:"assets/images/items/aether_wing.svg",kind:"accessory",price:0,desc:"雲海の風を宿した羽。HPとMP、素早さ、賢さが上がる。",stat:{hp:35,mp:18,spd:16,wis:10}},
    zenith_core:{name:"天頂竜の核",icon:"☀️",image:"assets/images/items/zenith_core.svg",kind:"accessory",price:0,desc:"ゼニスドラゴンの光を凝縮した核。すべての能力を大きく高める。",stat:{hp:80,mp:36,atk:18,def:18,spd:16,wis:18}},
  };
  P.SHOP_ITEMS = ["force_ring","guard_stone","swift_feather","mage_charm","life_drop","mana_shell"];
  P.DROPS = {
    plim:[{id:"life_drop",rate:8}], leafling:[{id:"swift_feather",rate:7}], puffbat:[{id:"mage_charm",rate:7}], pebblon:[{id:"guard_stone",rate:9}],
    embercub:[{id:"force_ring",rate:9}], aquan:[{id:"mana_shell",rate:9}], thornhog:[{id:"force_ring",rate:8},{id:"swift_feather",rate:5}], frostpup:[{id:"frost_scale",rate:3},{id:"mana_shell",rate:9}],
    mossking:[{id:"woodland_crown",rate:28},{id:"life_drop",rate:18}], cindrake:[{id:"volcano_fang",rate:8},{id:"force_ring",rate:14}], gearbit:[{id:"ore_core",rate:7},{id:"guard_stone",rate:14}],
    gloomoth:[{id:"mage_charm",rate:13},{id:"mana_shell",rate:9}], snowcat:[{id:"frost_scale",rate:5},{id:"swift_feather",rate:14}], voltfox:[{id:"arc_core",rate:4},{id:"swift_feather",rate:14}],
    orelord:[{id:"ore_core",rate:28},{id:"guard_stone",rate:18}], luminel:[{id:"tide_pearl",rate:7},{id:"mage_charm",rate:14}], crystagon:[{id:"astral_orb",rate:4},{id:"volcano_fang",rate:8}],
    icetortoise:[{id:"frost_scale",rate:8},{id:"guard_stone",rate:16}], ironmantis:[{id:"arc_core",rate:7},{id:"force_ring",rate:14}],
    tidalseraph:[{id:"tide_pearl",rate:28},{id:"mana_shell",rate:18}], volcazard:[{id:"volcano_fang",rate:28},{id:"force_ring",rate:18}], duskwolf:[{id:"astral_orb",rate:5},{id:"mage_charm",rate:18}],
    frostlevia:[{id:"frost_scale",rate:35},{id:"tide_pearl",rate:12}], arcautomaton:[{id:"arc_core",rate:35},{id:"ore_core",rate:12}], astralwyrm:[{id:"astral_orb",rate:35},{id:"tide_pearl",rate:15},{id:"volcano_fang",rate:15}],
    prismdragon:[{id:"prism_feather",rate:40},{id:"astral_orb",rate:20},{id:"arc_core",rate:15},{id:"frost_scale",rate:15}],
    poisonplim:[{id:"mire_orb",rate:5},{id:"mana_shell",rate:8}], toxicshroom:[{id:"mire_orb",rate:8},{id:"mage_charm",rate:12}], sludgecko:[{id:"mire_orb",rate:8},{id:"life_drop",rate:12}], venomwing:[{id:"venom_crown",rate:5},{id:"swift_feather",rate:12}], venomhydra:[{id:"venom_crown",rate:36},{id:"mire_orb",rate:14}], gearslime:[{id:"ancient_gear",rate:4},{id:"guard_stone",rate:12}], steelbug:[{id:"ancient_gear",rate:5},{id:"force_ring",rate:12}], thunderdrone:[{id:"arc_core",rate:7},{id:"swift_feather",rate:12}], corewalker:[{id:"ancient_gear",rate:9},{id:"ore_core",rate:8}], arkmachine:[{id:"ancient_gear",rate:36},{id:"arc_core",rate:16}], venomchimera:[{id:"venom_crown",rate:20},{id:"astral_orb",rate:10}], omegaframe:[{id:"ancient_gear",rate:20},{id:"prism_feather",rate:10}]    ,corallume:[{id:"abyss_pearl",rate:7},{id:"mana_shell",rate:12}], abyssfin:[{id:"abyss_pearl",rate:8},{id:"tide_pearl",rate:10}], shellgolem:[{id:"abyss_pearl",rate:6},{id:"guard_stone",rate:12}], pearlseraph:[{id:"abyss_pearl",rate:10},{id:"prism_feather",rate:4}], abysslevia:[{id:"leviathan_scale",rate:38},{id:"abyss_pearl",rate:18}], impfang:[{id:"demon_horn",rate:7},{id:"swift_feather",rate:12}], hellknight:[{id:"demon_horn",rate:9},{id:"force_ring",rate:12}], doomgazer:[{id:"demon_horn",rate:12},{id:"mage_charm",rate:12}], chaoswyrm:[{id:"demon_horn",rate:14},{id:"astral_orb",rate:8}], demonlord:[{id:"chaos_crown",rate:40},{id:"demon_horn",rate:20}]
,
    // v7.4 batch1 monster drops
    budbunny:[{id:"swift_feather",rate:6},{id:"life_drop",rate:5}],
    cavemole:[{id:"guard_stone",rate:8},{id:"ore_core",rate:3}],
    dewplim:[{id:"mana_shell",rate:7},{id:"life_drop",rate:5}],
    reefowl:[{id:"swift_feather",rate:7},{id:"tide_pearl",rate:3}],
    ashimp:[{id:"force_ring",rate:7},{id:"demon_horn",rate:3}],
    cinderhorn:[{id:"volcano_fang",rate:7},{id:"force_ring",rate:10}],
    cragbear:[{id:"ore_core",rate:8},{id:"guard_stone",rate:12}],
    lumenowl:[{id:"mage_charm",rate:8},{id:"arc_core",rate:4}],
    snowfairy:[{id:"frost_scale",rate:5},{id:"mana_shell",rate:8}],
    sparkbug:[{id:"swift_feather",rate:6},{id:"arc_core",rate:3}],
    miretoad:[{id:"mire_orb",rate:8},{id:"mana_shell",rate:6}],
    gearcat:[{id:"ancient_gear",rate:5},{id:"swift_feather",rate:8}],
    abyssjelly:[{id:"abyss_pearl",rate:6},{id:"mage_charm",rate:8}],
    venomqueen:[{id:"venom_crown",rate:10},{id:"mire_orb",rate:12}],
    thunderlion:[{id:"arc_core",rate:10},{id:"force_ring",rate:10}],
    forgegolem:[{id:"ancient_gear",rate:11},{id:"ore_core",rate:10}],
    glacierfang:[{id:"frost_scale",rate:13},{id:"leviathan_scale",rate:4}],
    solarwyrm:[{id:"prism_feather",rate:6},{id:"astral_orb",rate:10}],
    nightmarestag:[{id:"demon_horn",rate:12},{id:"venom_crown",rate:7}],
    titanplim:[{id:"prism_feather",rate:10},{id:"chaos_crown",rate:4},{id:"life_drop",rate:16}],
    cloudplim:[{id:"sky_shard",rate:8},{id:"mana_shell",rate:12}],
    sunhare:[{id:"sky_shard",rate:8},{id:"swift_feather",rate:12}],
    galegryph:[{id:"aether_wing",rate:5},{id:"swift_feather",rate:14}],
    skywarden:[{id:"sky_shard",rate:10},{id:"ancient_gear",rate:8}],
    stormdjinn:[{id:"aether_wing",rate:12},{id:"arc_core",rate:10}],
    aethergolem:[{id:"sky_shard",rate:16},{id:"ore_core",rate:12}],
    seraphalcon:[{id:"aether_wing",rate:16},{id:"prism_feather",rate:8}],
    heavenscale:[{id:"aether_wing",rate:20},{id:"astral_orb",rate:12}],
    zenithdragon:[{id:"zenith_core",rate:42},{id:"aether_wing",rate:22}],
  };
})();
