(() => {
  "use strict";
  const P = window.MonsterLinksParts = window.MonsterLinksParts || {};
  P.STAGES = [
    {id:"meadow",image:"assets/images/stages/meadow.png",name:"はじまり草原",icon:"🌿",req:1,unlock:1,desc:"弱い自然系が多い。スカウト練習に最適。",enemies:["plim","leafling","puffbat","budbunny"],min:1,max:3,gold:[11,18],exp:[16,26],scout:42,danger:1,traits:["自然","スライム","飛行"],drops:["woodland_crown","force_ring","life_drop"],hint:"まずはスカウト練習。火力よりも仲間を増やすことを優先。",boss:{id:"mossking",level:4,unlockWins:2,gold:70,exp:115,scout:14}},
    {id:"cave",image:"assets/images/stages/cave.png",name:"こだま洞くつ",icon:"🪨",req:3,unlock:2,desc:"守備が高い敵が増える。魔法やスカウトを使い分けよう。",enemies:["pebblon","puffbat","thornhog","cavemole"],min:3,max:6,gold:[20,34],exp:[28,46],scout:34,danger:2,traits:["物質","飛行","けもの"],drops:["ore_core","guard_stone","force_ring"],hint:"守備が高い敵が多い。賢さ系スキルや回復役がいると安定。",boss:{id:"orelord",level:7,unlockWins:2,gold:120,exp:190,scout:11}},
    {id:"brook",image:"assets/images/stages/brook.png",name:"しずく湖畔",icon:"💧",req:5,unlock:3,desc:"回復や水魔法を使う敵が登場。長期戦に注意。",enemies:["aquan","leafling","gloomoth","dewplim","reefowl"],min:5,max:8,gold:[32,52],exp:[48,76],scout:28,danger:2,traits:["水","自然","闇"],drops:["tide_pearl","mana_shell","mage_charm"],hint:"水・回復系が多め。長期戦になる前に火力で押し切りたい。",boss:{id:"tidalseraph",level:10,unlockWins:3,gold:185,exp:310,scout:8}},
    {id:"volcano",image:"assets/images/stages/volcano.png",name:"ほむら火山",icon:"🔥",req:8,unlock:4,desc:"攻撃力が高い火の敵が中心。守備と回復が重要。",enemies:["embercub","cindrake","gearbit","ashimp","cinderhorn"],min:8,max:12,gold:[42,70],exp:[62,98],scout:18,danger:3,traits:["火","竜","機械"],drops:["volcano_fang","force_ring","life_drop"],hint:"攻撃力が高い。水属性や守備高めの仲間を連れて行くと楽。",boss:{id:"volcazard",level:14,unlockWins:4,gold:230,exp:380,scout:5}},
    {id:"tower",image:"assets/images/stages/tower.png",name:"星晶の塔",icon:"✨",req:12,unlock:5,desc:"配合で作った強力な仲間が活躍する終盤ステージ。",enemies:["gloomoth","luminel","crystagon","cragbear","lumenowl"],min:12,max:17,gold:[70,120],exp:[100,165],scout:13,danger:3,traits:["闇","光","竜"],drops:["astral_orb","mage_charm","mana_shell"],hint:"配合モンスターが活躍しやすい。属性相性を見て主力を選ぶ。",boss:{id:"astralwyrm",level:20,unlockWins:5,gold:400,exp:650,scout:3}},
    {id:"snowfield",image:"assets/images/stages/snowfield.png",name:"霜降り雪原",icon:"❄️",req:16,unlock:6,desc:"冷気と高速モンスターが多い上級エリア。火・光の火力があると進めやすい。",enemies:["frostpup","snowcat","icetortoise","luminel","snowfairy"],min:17,max:24,gold:[110,175],exp:[170,260],scout:11,danger:4,traits:["水","飛行","光"],drops:["frost_scale","swift_feather","guard_stone"],hint:"冷気系と素早い敵が多い。火・光の火力があると進めやすい。",boss:{id:"frostlevia",level:25,unlockWins:4,gold:620,exp:980,scout:3}},
    {id:"thunder_ruins",image:"assets/images/stages/thunder_ruins.png",name:"雷鳴遺跡",icon:"⚡",req:21,unlock:7,desc:"機械系と雷属性の敵が集まる遺跡。守備だけでなく素早さも重要。",enemies:["gearbit","voltfox","ironmantis","gloomoth","sparkbug"],min:22,max:30,gold:[150,230],exp:[240,360],scout:9,danger:4,traits:["機械","光","闇"],drops:["arc_core","swift_feather","force_ring"],hint:"機械系が多い。素早さと攻撃の両方を意識した編成が有効。",boss:{id:"arcautomaton",level:31,unlockWins:5,gold:820,exp:1320,scout:2}},
    {id:"prism_sanctuary",image:"assets/images/stages/prism_sanctuary.png",name:"虹晶聖域",icon:"🌈",req:28,unlock:8,desc:"強敵だらけの最終級エリア。配合・装備・属性相性を総動員して挑もう。",enemies:["duskwolf","crystagon","tidalseraph","volcazard","frostlevia"],min:30,max:40,gold:[230,360],exp:[380,580],scout:7,danger:5,traits:["竜","光","水","火"],drops:["prism_feather","astral_orb","mage_charm"],hint:"終盤の総合力チェック。装備・配合・属性相性を整えて挑む。",boss:{id:"prismdragon",level:42,unlockWins:6,gold:1400,exp:2200,scout:1}},
    {id:"poison_bog",image:"assets/images/stages/poison_bog.png",name:"毒霧の沼地",icon:"☣️",req:34,unlock:9,desc:"毒と呪いをまとう魔物が潜む沼地。回復役と闇耐性が欲しい。",enemies:["poisonplim","toxicshroom","sludgecko","venomwing","miretoad"],min:36,max:46,gold:[300,450],exp:[480,720],scout:6,danger:4,traits:["闇","自然","水"],drops:["mire_orb","mana_shell","guard_stone"],hint:"闇・毒の雰囲気が強いエリア。HPと回復手段を厚めにする。",boss:{id:"venomhydra",level:48,unlockWins:5,gold:1700,exp:2700,scout:1}},
    {id:"machine_city",image:"assets/images/stages/machine_city.png",name:"古代機械都市",icon:"⚙️",req:39,unlock:10,desc:"朽ちた都市で機械兵が目覚める。高守備と雷攻撃への対策が重要。",enemies:["gearslime","steelbug","thunderdrone","corewalker","gearcat"],min:42,max:54,gold:[380,560],exp:[620,920],scout:5,danger:5,traits:["機械","物質","光"],drops:["ancient_gear","arc_core","swift_feather"],hint:"高守備・高火力の機械系が多い。賢さ攻撃も使えると楽。",boss:{id:"arkmachine",level:57,unlockWins:6,gold:2200,exp:3400,scout:1}}
    ,{id:"deep_sea_temple",image:"assets/images/stages/deep_sea_temple.png",name:"深海神殿",icon:"🌊",req:46,unlock:11,desc:"海底に沈んだ古代神殿。水・光属性の強敵が多く、長期戦になりやすい。",enemies:["corallume","abyssfin","shellgolem","pearlseraph","abyssjelly"],min:48,max:62,gold:[520,760],exp:[840,1250],scout:5,danger:5,traits:["水","光","竜"],drops:["abyss_pearl","leviathan_scale","tide_pearl"],hint:"水と光の上位エリア。長期戦を見越してMPと回復を確保。",boss:{id:"abysslevia",level:66,unlockWins:6,gold:3400,exp:5200,scout:1}},
    {id:"demon_gate",image:"assets/images/stages/demon_gate.png",name:"魔界門",icon:"🕳️",req:54,unlock:12,desc:"魔界へ通じる門。闇属性の高火力モンスターが出現する終盤エリア。",enemies:["impfang","hellknight","doomgazer","chaoswyrm"],min:56,max:70,gold:[660,980],exp:[1080,1600],scout:4,danger:5,traits:["闇","竜","高火力"],drops:["demon_horn","chaos_crown","astral_orb"],hint:"闇属性の高火力エリア。光属性や耐久寄りの装備で挑みたい。",boss:{id:"demonlord",level:76,unlockWins:7,gold:5000,exp:7600,scout:1}},
    {id:"sky_ruins",image:"assets/images/stages/sky_ruins.svg",name:"天空遺跡",icon:"☁️",req:68,unlock:13,desc:"魔界門の先で見つかった雲海の古代遺跡。光・翼・機械の精鋭が天頂を守る。",enemies:["cloudplim","sunhare","galegryph","skywarden","stormdjinn"],min:68,max:82,gold:[820,1220],exp:[1360,2040],scout:8,danger:5,traits:["光","翼","機械","高速"],drops:["sky_shard","aether_wing","prism_feather"],hint:"通常探索はLv68が目安。ボス戦は回復役を入れ、天空配合の仲間かLv72前後の主力で挑もう。",boss:{id:"zenithdragon",level:86,unlockWins:7,gold:6800,exp:10200,scout:1}}
  ];
})();
